/**
 * Mapping from Good id to its icon filename in `public/icons/`.
 *
 * The PNGs are sourced from https://github.com/Sovgut/avorion-tools (CC-BY).
 * They live under `public/icons/{file}.png` and are served at `/icons/{file}.png`
 * by Nuxt's static asset pipeline. Several goods intentionally share the same
 * file (e.g. gold/silver/platinum all use `metal-bar`) — that mirrors the
 * upstream choice.
 *
 * Use {@link goodIconUrl} to resolve a URL with a generic fallback.
 */
const ICON_FILES: Record<string, string> = {
  // raw
  'ore': 'rock',
  'coal': 'fossil-fuel',
  'raw-oil': 'oil-drum',
  'silicon': 'silicium',
  'copper': 'copper',
  'lead': 'lead',
  'zinc': 'zinc',
  'aluminum': 'aluminium',
  'gold': 'metal-bar',
  'silver': 'metal-bar',
  'platinum': 'metal-bar',
  'mineral': 'rock',
  'gem': 'crystal',
  'diamond': 'crystal',

  // basic
  'water': 'water',
  'energy-cell': 'battery-pack-alt',
  'hydrogen': 'hydrogen',
  'helium': 'helium',
  'neon': 'neon',
  'chlorine': 'chlorine',
  'fluorine': 'fluorine',
  'nitrogen': 'nitrogen',
  'oxygen': 'oxygen',
  'wheat': 'wheat',
  'corn': 'wheat',
  'rice': 'wheat',
  'potato': 'wheat',
  'fruit': 'wheat',
  'vegetable': 'wheat',
  'plant': 'wheat',
  'wood': 'wheat',
  'cocoa': 'wheat',
  'coffee': 'wheat',
  'tea': 'wheat',
  'spices': 'wheat',
  'fungus': 'wheat',
  'plankton': 'wheat',
  'bio-gas': 'bio-gas',
  'cattle': 'cattle',
  'sheep': 'sheep',
  'fish': 'cattle',
  'meat': 'cattle',
  'dairy': 'cattle',
  'leather': 'fabric',
  'glass': 'metal-disc',
  'steel': 'i-beam',
  'oil': 'oil-drum',
  'plastic': 'cargo-hold',
  'rubber': 'cubes',
  'chemicals': 'chemical',
  'acid': 'chemical',
  'solvent': 'chemical',
  'coolant': 'chemical',
  'toxic-waste': 'chemical',
  'carbon': 'carbon',
  'fabric': 'fabric',
  'paint': 'paint',
  'adhesive': 'adhesive',
  'scrap-metal': 'scrap-metal',
  'crystal': 'crystal',
  'fuel': 'fuel',
  'ammunition': 'ammo-box',
  'ammunition-s': 'ammunition-s',
  'ammunition-m': 'ammunition-s',
  'ammunition-l': 'ammunition-l',
  'fertilizer': 'chemical',
  'paper': 'cargo-hold',
  'food': 'cargo-hold',
  'food-bar': 'cargo-hold',
  'protein': 'cargo-hold',
  'luxury-food': 'cargo-hold',
  'beer': 'martini',
  'wine': 'martini',
  'liquor': 'martini',
  'book': 'cargo-hold',
  'clothes': 'fabric',

  // mid
  'conductor': 'conductor',
  'wire': 'wire',
  'semi-conductor': 'semi-conductor',
  'transformator': 'grenade',
  'servo': 'servo',
  'steel-tube': 'steel-tube',
  'high-pressure-tube': 'high-pressure-tube',
  'metal-plate': 'metal-scales',
  'electro-magnet': 'electro-magnet',
  'microchip': 'microchip',
  'nanobot': 'nanobots',
  'energy-container': 'electric',
  'plasma-cell': 'plasma-cell',
  'energy-tube': 'energy-tube',
  'power-unit': 'power-unit',
  'turbine': 'turbine',
  'gauss-rail': 'gauss-rail',
  'solar-cell': 'solar-cell',
  'solar-panel': 'satellite-solarpanel',
  'display': 'microchip',
  'targeting-card': 'microchip',
  'laser-head': 'laser-head',
  'gun': 'bolter-gun',
  'warhead': 'warhead',
  'fusion-core': 'electric',
  'high-capacity-lens': 'laser-head',
  'drill': 'tools',

  // adv
  'laser-compressor': 'laser-compressor',
  'laser-modulator': 'laser-modulator',
  'energy-inverter': 'energy-inverter',
  'antigrav-unit': 'antigrav-unit',
  'targeting-system': 'targeting-system',
  'processor': 'processor',
  'energy-generator': 'electric',
  'fusion-generator': 'electric',
  'force-generator': 'electric',
  'antigrav-generator': 'antigrav-unit',
  'computation-mainframe': 'microchip',
  'explosive-charge': 'warhead',
  'electromagnetic-charge': 'warhead',
  'teleporter': 'electric',

  // end
  'medical-supplies': 'medical-supplies',
  'tools': 'tools',
  'body-armor': 'kevlar-vest',
  'vehicle': 'apc',
  'war-robot': 'missile-mech',
  'mining-robot': 'robot-golem',
  'drone': 'robot-golem',
  'satellite': 'satellite',
  'jewelry': 'metal-bar',
  'electron-accelerator': 'electron-accelerator',
  'proton-accelerator': 'electron-accelerator',
  'neutron-accelerator': 'electron-accelerator',

  // hi
  'rocket': 'rocket',
  'industrial-tesla-coil': 'industrial-tesla-coil',
  'military-tesla-coil': 'industrial-tesla-coil',
}

const FALLBACK = '/icons/rock.png'

export function goodIconUrl(id: string): string {
  const file = ICON_FILES[id]
  return file ? `/icons/${file}.png` : FALLBACK
}
